development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: mxfeature
  username: postgres
  password: postgres
  template: template0
  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: mxfeature
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: mxfeature
  pool:     5
  username: postgres
  password: postgres
  template: template0